listings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    path('', index, name = 'index'),
    path('submit/', SubmitView.as_view(), name = 'submit'),
    path('listing/<int:pk>', ListingDetail.as_view(), name = 'listing'),
    path('search/', search, name = 'search'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.timezone import now
from django.urls import reverse

class Location(models.Model):
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.location


class Condition(models.Model):
    condition = models.CharField(max_length=100)

    def __str__(self):
        return self.condition

class ListingType(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name


class Listing(models.Model):
    title = models.CharField(max_length=200, verbose_name = 'Listing Title')
    category = models.ForeignKey(ListingType, on_delete = models.CASCADE, verbose_name = 'Category')
    price = models.IntegerField(verbose_name = 'Price (in Rupees)')
    location = models.ForeignKey(Location, on_delete = models.CASCADE, verbose_name = 'Location')
    condition = models.ForeignKey(Condition, on_delete = models.CASCADE, verbose_name = 'Item Condition')
    description = models.TextField(verbose_name = 'Description')
    photo = models.ImageField(upload_to='images')

    sold = models.BooleanField(default = False)

    op = models.CharField(max_length = 200, verbose_name = 'Your Name')
    email = models.EmailField(verbose_name = 'Your Email Address')
    phone = models.BigIntegerField(verbose_name = 'Contact Number (optional)',
                                   blank = True, null = True)

    created = models.DateTimeField(default = now)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def name(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse('main:listing', kwargs = {'pk': self.pk})

main/forms.py
from django import forms

from .models import Listing

class SearchForm(forms.Form):
    query = forms.CharField(max_length = 200)
    sort_by = forms.CharField(max_length = 100)

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'category', 'price', 'location', 'condition',
                  'description', 'photo', 'op', 'email', 'phone']

main/views.py
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from .forms import *
from .models import *

def index(request):
    listings = Listing.objects.filter(sold = False)
    # print("\n\n")
    # print(f"listings:   {listings}")
    # print(f"type(listings):   {type(listings)}")
    # for listing in listings:
    #     print("\n")
    #     print(f"\tlisting:   {listing}")
    #     print(f"\ttype(listing):   {type(listing)}")
    #     print("\n")
    # print("\n\n")
    return render(request, 'index.html', {'listings': listings})

class SubmitView(CreateView):
    form_class = ListingForm
    template_name = 'submit.html'

class ListingDetail(DetailView):
    model = Listing
    template_name = 'listing.html'

def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            search_string = form.cleaned_data['query']

            words = search_string.lower().split(' ')
            vector = SearchVector('title', 'category__name', 'location__location', 
                    'condition__condition', 'description', 'op')

            query = SearchQuery(words[0])
            for word in words[1:]:
                query = query | SearchQuery(word)

            sort_by = form.cleaned_data['sort_by']
            sort_by = ('-rank',) if sort_by == '-rank' else ('-rank', sort_by)
            listings = Listing.objects.annotate(rank=SearchRank(vector,
                query)).order_by(*sort_by)

            return render(request, 'results.html',
                    {'search_string': search_string, 'listings': listings})

    return HttpResponseRedirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/styleBootstrap.css' %}">
	<script src="https://kit.fontawesome.com/51158303ea.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
		crossorigin="anonymous"></script>
	{% block head %}{% endblock head %}
	<title>
		{% block title %}{% endblock %} | NISER Listings
	</title>
</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'main:index' %}">NISER Listings</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" href="{% url 'main:submit' %}">Sell</a>
					</li>
				</ul>
				<form action="{% url 'main:search' %}" method="GET">
					<input class="formCustom" type="search" name="query" placeholder="Search"
						style="height:fit-content;">
					<input class="btn btn-outline-light" type="submit" value="Search">
					<br>
					<p hidden>Sort by:
						  <input type="radio" id="Relevance" name="sort_by" value="-rank" checked="checked">
						  <label for="Relevance">Relevance</label>
					</p>
				</form>
			</div>
		</div>
	</nav>

	{% block Search %}{% endblock %}
	<!-- <hr> -->


	<main>
		{% if messages %}
		<ul>
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		<div class="all">
			{% block content %}
			{% endblock %}
		</div>
	</main>

	<!-- Footer -->
	<section id="footer">
		<div class="footer container">
			<h2>NISER Listings</h2>
			<a class="social git" href="#" title="Link to GitHub" target="_blank"><i class="fab fa-git-alt"></i></a>
			<a class="social mail" href="#" title="Mail Us" target="_blank"><i class="far fa-envelope"></i></a>
			<h2>Software Development Group</h2>
			<h3>National Institute of Science Education and Research</h3>
			<h4>Bhubaneswar, India</h4>
		</div>
	</section>
	<!-- End Footer -->

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block Search %}
	<div class="searchItem text-center">
		<img height="250px" src="{% static 'pics/niser_logo.png' %}">
		<h1>NISER Listings</h1>
        <p>One person's trash is another person's treasure.</p>

		<form action="{% url 'main:search' %}" method="GET">
			<input class="formCustom" type="search" name="query" placeholder="Search">
			<input type="submit" value="Search" class="btn btn-primary mb-2">
			<br>
			<p><br>Sort by:<br>
				<input type="radio" id="Relevance" name="sort_by" value="-rank" checked="checked">
				<label for="Relevance">Relevance</label><br>
				<input type="radio" id="priceLowFirst" name="sort_by" value="price">
				<label for="priceLowFirst">Price Increasing</label><br>
				<input type="radio" id="priceHighFirst" name="sort_by" value="-price">
				<label for="priceHighFirst">Price Decreasing</label></p>

		</form>
		<a href="{% url 'main:submit' %}">
			<button type="button" class="btn btn-primary m-3" style="border-radius: 15px;">
				<h1>Sell</h1>
			</button>
		</a>

		</form>

	</div>
{% endblock %}

{% block content %}

	<h2 class="text-center my-xxl-5">Find your treasure...</h2>

	{% if listings %}
	<div class="container my-xxl-5">
		<div class="row row-cols-1 row-cols-md-3 g-4">
			{% for item in listings %}
			<div class="col">
				<a href="{% url 'main:listing' item.id %}" style="text-decoration: none; color: #340c5a;">
					<div class="card">
						<div class="custom-card-img-top" style="background-image: url('{{ item.photo.url }}')"></div>
						
						{% comment %} <img src="{{ item.photo.url }}" class="card-img-top custom-card-img-top"> {% endcomment %}
						<div class="card-body">
							<h5 class="card-title">{{ item }}</h5>
							<p class="card-text">Price: ₹ {{ item.price }}</p>
							{% if item.description|length > 400 %}
							<p class="card-text justify">{{ item.description|truncatechars:400 }} <strong>&ltcontd.&gt</strong></p>
							{% else %}
							<p class="card-text">{{ item.description }}</p>
							{% endif %}
						</div>

					</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>

	{% else %}
	<p>There are no listings right now.</p>

	{% endif %}

{% endblock %}

templates/listing.html
{% extends 'base.html' %}

{% block title %}
{{ listing }}
{% endblock %}

{% block content %}
<div class="listingDetails">
	<aside class="side left">
		{% if listing.photo %}
		<br><img class="sticky-top" src="{{ listing.photo.url }}" width="100%"><br>
		{% else %}
		<p>[image not uploaded]</p>
		{% endif %}
	</aside>
	<aside class="side right">
		<h1>{{ listing }}</h1>
		<table>
			<tr>
				<th>Price:</th>
				<td> ₹ {{ listing.price }}</td>
			</tr>

			<tr>
				<th>Condition:&emsp;</th>
				<td>{{ listing.condition }}</td>
			</tr>

			<tr>
				<th>Location:&emsp;</th>
				<td>{{ listing.location }}</td>
			</tr>

			<tr>
				<th>Listed by:&emsp;</th>
				<td>{{ listing.op }}</td>
			</tr>

			<tr>
				<th>Email:&emsp;</th>
				<td><a href="mailto:{{ listing.email }}">{{ listing.email }}</a></td>
			</tr>

			<tr>
				<th>Phone:&emsp;</th>
				<td><a href="tel:{{ listing.phone }}">{{ listing.phone }}</a></td>
			</tr>
		</table>
		<br>
		<strong>Description:&ensp;</strong>
		{{ listing.description }}
		<br>
	</aside>
</div>
{% endblock %}

templates/results.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Search Results
{% endblock %}

{% block content %}

{% if listings %}

<h2>Search results for "{{ search_string }}"</h2>

<div class="container my-4">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for item in listings %}
    <div class="col">
      <a href="{% url 'main:listing' item.id %}" style="text-decoration: none; color: #340c5a;">
        <div class="card">
          
						<div class="custom-card-img-top" style="background-image: url('{{ item.photo.url }}')"></div>
          <div class="card-body">
            <h5 class="card-title">{{ item }}</h5>
            <p class="card-text">Price: ₹ {{ item.price }}</p>
            {% if item.description|length > 400 %}
            <p class="card-text justify">{{ item.description|truncatechars:400 }} <strong>&ltcontd.&gt</strong></p>
            {% else %}
            <p class="card-text">{{ item.description }}</p>
            {% endif %}
          </div>
      </a>
    </div>
  </div>
  {% endfor %}
</div>

{% else %}
<h2>Nothing found for "{{ search_string }}"</h2>

{% endif %}

{% endblock %}

templates/submit.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/styleSubmit.css' %}">

{% endblock head %}

{% block title %}Submit a Listing{% endblock %}




{% block content %}
<div class="sell-form">
    <h2>Submit a Listing</h2>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            {{ field.errors }}
            <div class="form-label">{{ field.label }}</div>

            {{ field }}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div style="text-align: center"><input type="submit" class="btn btn-primary" value="Submit"></div>
    </form>
</div>
{% endblock %}